{% set name = "fastcan" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fastcan-{{ version }}.tar.gz
  sha256: d3c36b86ce79b739e0e58c582a8cab2ce63187d72b0c1a5aacfa5c72671575a3

build:
  number: 0
  skip: true  # [py<39]
  skip: true  # [python_impl == "pypy"]

requirements:
  build:
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - python                                # [build_platform != target_platform]
    - cython                                # [build_platform != target_platform]
    - meson-python                          # [build_platform != target_platform]
    - ninja
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - python
    - meson-python
    - cython
    - scikit-learn >=1.5.0,<1.6
    - python-build
    - pip
    # See https://github.com/conda-forge/openmp-feedstock/issues/126
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  run:
    - python
    - scikit-learn >=1.5.0,<1.6

test:
  imports:
    - fastcan
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://fastcan.readthedocs.io/en/latest/
  summary: A fast canonical-correlation-based feature selection method
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/MatthewSZhang/fastcan/

extra:
  recipe-maintainers:
    - MatthewSZhang
