{% set name = "fastcan" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fastcan-{{ version }}.tar.gz
  sha256: da50d251202b417631cdd8dc150856a8c4be8bbc72e79fecc71437ad7c95a053

build:
  number: 1
  skip: true  # [py<39]
  skip: true  # [python_impl == "pypy"]

requirements:
  build:
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - python                                # [build_platform != target_platform]
    - cython                                # [build_platform != target_platform]
    - meson-python                          # [build_platform != target_platform]
    - ninja
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - python
    - meson-python
    - cython
    - scikit-learn >=1.5.0,<1.6
    - python-build
    - pip
  run:
    - python
    - scikit-learn >=1.5.0,<1.6

test:
  imports:
    - fastcan
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://fastcan.readthedocs.io/en/latest/
  summary: A fast canonical-correlation-based feature selection method
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/MatthewSZhang/fastcan/

extra:
  recipe-maintainers:
    - MatthewSZhang
