{% set name = "fastcan" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fastcan-{{ version }}.tar.gz
  sha256: fbd9cb29c606d0809c5eb491755308ae9f56bf256eab4cf5d66d9cf2b01b62a1

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  skip: true  # [py<39]
  skip: true  # [python_impl == "pypy"]

requirements:
  build:
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - python                                # [build_platform != target_platform]
    - cython                                # [build_platform != target_platform]
    - meson-python                          # [build_platform != target_platform]
    - ninja                                 # [build_platform != target_platform]
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - python
    - meson-python
    - ninja
    - cython
    - python-build
    - pip
  run:
    - python
    - scikit-learn >=1.5.0,<1.6

test:
  imports:
    - fastcan
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://fastcan.readthedocs.io/en/latest/
  summary: A fast canonical-correlation-based feature selection method
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MatthewSZhang
